version: "3.9"
services:
  chanchito:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - monguito
    volumes:
      - .:/app
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data
volumes:
  mongo-data: